# Generated by Django 6.0.4 on 2026-06-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ATTENDEE', 'Attendee'), ('ORGANISER', 'Organiser'), ('ADMIN', 'Admin')], default='ATTENDEE', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', False), _connector='OR'), name='deleted_user_inactive'),
        ),
    ]
